TOP=../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
DB += array.db
DB += calc.db
DB += double.db
DB += enum.db
DB += float.db
DB += int16.db
DB += int32.db
DB += int64.db
DB += int8.db
DB += longString.db
DB += simpleBusy.db
DB += stringArray.db
DB += string.db
DB += uint16.db
DB += uint32.db
DB += uint8.db
DB += uint64.db

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

