TOP = ..
include $(TOP)/configure/CONFIG
DIRS += $(wildcard *ioc*)
DIRS += $(wildcard as*)
DIRS += $(wildcard example*)
DIRS += $(wildcard many*)
DIRS += caLink
include $(EPICS_BASE)/configure/RULES_DIRS

