TOP = ..
include $(TOP)/configure/CONFIG
DIRS += caLink
DIRS += fastcalc
DIRS += DBRecordTypes
DIRS += manyDBRecords
DIRS += manyPVRecords
DIRS += addremovetrace
include $(EPICS_BASE)/configure/RULES_DIRS

