#!/bin/sh
pvput -r value booleanASL0 true
pvget -r value booleanASL0
pvput -r value booleanASL1 true
pvget -r value booleanASL1
pvput -r value byteASL0 1
pvget -r value byteASL0
pvput -r value byteASL1 1
pvget -r value byteASL1
pvput -r value shortASL0 1
pvget -r value shortASL0
pvput -r value shortASL1 1
pvget -r value shortASL1
pvput -r value intASL0 1
pvget -r value intASL0
pvput -r value intASL1 1
pvget -r value intASL1
pvput -r value longASL0 1
pvget -r value longASL0
pvput -r value longASL1 1
pvget -r value longASL1
pvput -r value ubyteASL0 1
pvget -r value ubyteASL0
pvput -r value ubyteASL1 1
pvget -r value ubyteASL1
pvput -r value ushortASL0 1
pvget -r value ushortASL0
pvput -r value ushortASL1 1
pvget -r value ushortASL1
pvput -r value uintASL0 1
pvget -r value uintASL0
pvput -r value uintASL1 1
pvget -r value uintASL1
pvput -r value ulongASL0 1
pvget -r value ulongASL0
pvput -r value ulongASL1 1
pvget -r value ulongASL1
pvput -r value floatASL0 1
pvget -r value floatASL0
pvput -r value floatASL1 1
pvget -r value floatASL1
pvput -r value doubleASL0 1
pvget -r value doubleASL0
pvput -r value doubleASL1 1
pvget -r value doubleASL1
pvput -r value stringASL0 1
pvget -r value stringASL0
pvput -r value stringASL1 1
pvget -r value stringASL1

