#!/bin/sh

pvput -r value booleanArrayASL0 [true,false,true]
pvget -r value booleanArrayASL0
pvput -r value booleanArrayASL1 [true,false,true]
pvget -r value booleanArrayASL1
pvput -r value byteArrayASL0 [1,2,3,4]
pvget -r value byteArrayASL0
pvput -r value byteArrayASL1 [1,2,3,4]
pvget -r value byteArrayASL1
pvput -r value shortArrayASL0 [1,2,3,4]
pvget -r value shortArrayASL0
pvput -r value shortArrayASL1 [1,2,3,4]
pvget -r value shortArrayASL1
pvput -r value intArrayASL0 [1,2,3,4]
pvget -r value intArrayASL0
pvput -r value intArrayASL1 [1,2,3,4]
pvget -r value intArrayASL1
pvput -r value longArrayASL0 [1,2,3,4]
pvget -r value longArrayASL0
pvput -r value longArrayASL1 [1,2,3,4]
pvget -r value longArrayASL1
pvput -r value ubyteArrayASL0 [1,2,3,4]
pvget -r value ubyteArrayASL0
pvput -r value ubyteArrayASL1 [1,2,3,4]
pvget -r value ubyteArrayASL1
pvput -r value ushortArrayASL0 [1,2,3,4]
pvget -r value ushortArrayASL0
pvput -r value ushortArrayASL1 [1,2,3,4]
pvget -r value ushortArrayASL1
pvput -r value uintArrayASL0 [1,2,3,4]
pvget -r value uintArrayASL0
pvput -r value uintArrayASL1 [1,2,3,4]
pvget -r value uintArrayASL1
pvput -r value ulongArrayASL0 [1,2,3,4]
pvget -r value ulongArrayASL0
pvput -r value ulongArrayASL1 [1,2,3,4]
pvget -r value ulongArrayASL1
pvput -r value floatArrayASL0 [1,2,3,4]
pvget -r value floatArrayASL0
pvput -r value floatArrayASL1 [1,2,3,4]
pvget -r value floatArrayASL1
pvput -r value doubleArrayASL0 [1,2,3,4]
pvget -r value doubleArrayASL0
pvput -r value doubleArrayASL1 [1,2,3,4]
pvget -r value doubleArrayASL1
pvput -r value stringArrayASL0 [1,2,3,4]
pvget -r value stringArrayASL0
pvput -r value stringArrayASL1 [1,2,3,4]
pvget -r value stringArrayASL1
